### ISSUE TITLE
Keep Maintaining Yearn Docs and Written Content [extension]

### ISSUE THREAD

**Issue by saltyfacu** [yearn/budget#103]
### Scope

This is a request to extend #90.

The scope of the proposal is:
- Docs
- Articles on medium
- Other marketing material
- Some small UI help

### Plan

The plan, as in #69 and #90, is to keep adding content to the docs and crafting new articles to onboard new users and highlight the main benefits of using Yearn.

I ask for a monthly grant for 3 months ending on  February 28th. 5000 DAI per month for 3 months. The stream is already created, we need to move the deadline.

### Deadline

2023-02-28

### People

Marco Worms: technical writer
Dark Ghosty: reviewing and helping with docs

### Money

A grant for Marco to continue writing articles proactively and adding new content to the docs site.

### Amount

15000 DAI

### Wallet address

0xB1d693B77232D88a3C9467eD5619FfE79E80BCCc

### Reporting

Weekly

**Comment by MarcoWorms** [comment]
## Devdocs

- https://github.com/yearn/yearn-devdocs/pull/276/files
  - minor PR fixing grammar, still needs some work because it found broken links

## Articles

- stETH artlcle was reviewed by many peers, still working on some issues! should be done by next week, here is the draft: https://hackmd.io/5L8BMw8WS-WdU2ncFZ4uzA 

## Vault Report

- Refined the code to fix all past week problems and generate something pretty, but I would like to send to Evan so he can chip in the design and make it even better

current design: 
![image](https://user-images.githubusercontent.com/7863230/204064276-65d0954b-0ec3-4bc3-9ec9-9ac353ec1c58.png)

**Comment by MarcoWorms** [comment]
## Devdocs
- reviewed jmonteer v3 docs specs, brought an introduction based on the contents of his medium article about v3 vaults and put it all together in the docs. I've aligned with him that we will move the specs from the github repo he is using today to the docs, so after proper review and merge we should link the old spec to the doc page.
  - https://github.com/yearn/yearn-devdocs/pull/291
- generate 0.4.5 docs + improve generation instructions
  - https://github.com/yearn/yearn-devdocs/pull/285 

## Articles
- Applied all reviews to https://hackmd.io/5L8BMw8WS-WdU2ncFZ4uzA and now corn sent it to Lido for a last check before we publish.
- Working on a draft for an article about "how is yearn different from celsius, gemini earn, blockfi, and ftx earn", I don't have much text yet but next week should have something about it!

## Vault report
- Talked to Evan this week and he is working on an improved design, waiting on his final design to apply all changes!

**Comment by MarcoWorms** [comment]
## Devdocs
- smol hotfix
  - https://github.com/yearn/yearn-devdocs/pull/296
- I'm building an infrastructure I hope to plug in our docs somehow. It uses GPT-Edit API to suggest grammar and other improvements to text added in new PRs. My hope is to improve the overall quality of copy on the docs by providing a tool that suggests improvements directly on the PR, but I would also like to maybe scan all the files in the repo and make one PR with many improvements on what already exists, so the tool can both help in work being done but can also keep scanning the docs for potential improvements
  - For example, this is a PR I made: https://github.com/MarcoWorms/actions-test/pull/37/files
  - And the bot make a grammar suggestion: https://github.com/MarcoWorms/actions-test/pull/37#issuecomment-1354241711
  - Suggestions doesn't have to be limited to typos and grammar, there are many prompts we can experiment with! I'm currently focusing on grammar though
  - Another usage we can extend this tool to make is generating docs using code from yearn repos. We can switch from using the Edit API to use the normal one

## Articles 
- The last month article is taking longer than usual to come out, but it's because it has many parts that needed review and in the end we sent to Lido for a last read before publishing, I've been chatting with corn this week about this but we didn't get a response yet, he is in contact with them so I let the comms on this with him.
- Started a new article: "Protect your yields with Ledger and Yearn", talking about why and how to use the new integration shipped this month!
  - Draft: https://hackmd.io/FEUufpxRRWyZg7GbaTnJ-Q?both

## Vault reports
- Applied adjustments over the week chatting with the team behind this endeavor
- I am owing a tutorial on how to run the generator so it doesn't depend on me to generate report every month, I hope to have this documented by next week!

**Comment by MarcoWorms** [comment]
## Devdocs

- Partner Tracker V2 Docs
  - https://github.com/yearn/yearn-devdocs/pull/297
- Yearn Exporter docs, started improving the readme
  -  https://github.com/yearn/yearn-exporter/pull/458
- DocuDroid still needs about a week of work, I want it to be a better UI for some standard gpt flows that I'm currently using to make docs

## Articles

- No news on the lido article yet
- "Protect your yields with Ledger and Yearn" is still being done:
  - https://hackmd.io/FEUufpxRRWyZg7GbaTnJ-Q?both

## Vault Reports
- Documented the report exporting process:
  - https://hackmd.io/I_bb7yzLQKGTGu4by8Wdeg
- On standby but ready to do any changes needed to the generator after we get more feedbacks on the report

**Comment by MarcoWorms** [comment]
I did not produce much this week but there are a lot of ongoing things waiting for reviews, so I'll list them all to keep track of it for next year! I think reviews are taking long mostly because of the end of the years holidays and all, but I things should move faster after Jan starts!

## DevDocs

### This Week

- https://github.com/yearn/yearn-devdocs/pull/298
- https://github.com/yearn/yearn-press-kit/pull/71
- Made this as a tweet but I think this should be somehow accessible easier in the docs, will try to make it in next week: https://twitter.com/MarcoWorms/status/1608826246900887558

### Ongoing

- https://github.com/yearn/yearn-devdocs/pull/291
  - (waiting for technical review) 
- https://github.com/yearn/yearn-devdocs/pull/297
  -  (waiting for review + gonna have more after this)
- https://github.com/yearn/yearn-exporter/pull/458
  - (waiting for review + gonna have more after this)

## Articles

this week I made a personal article on explorations of GPT and some examples/tests happen with yearn docs, it's not something 100% yearn but I think it has some overlap (because I will increase tests on docs as I find more use cases) https://medium.com/p/83a6ebb81282#a864-ac812b9aa737

### Ongoing

- Protect yields with yearn+ledger (draft but getting close to finish)
  - https://hackmd.io/FEUufpxRRWyZg7GbaTnJ-Q?both
- Lido Case Study (taking a bit longer to review than usual, we sent to Lido I think the end of year context made it slower) 
  - https://hackmd.io/5L8BMw8WS-WdU2ncFZ4uzA

**Comment by MarcoWorms** [comment]
## DevDocs

- Permissionless Vaults docs done and merged!
  - https://github.com/yearn/yearn-devdocs/pull/299
- Partner tracker v2 vaults should be merged soon, waiting for a last review
  - https://github.com/yearn/yearn-devdocs/pull/297
- Working on Dank Mids docs with bob:
  - https://github.com/BobTheBuidler/dank_mids/pull/39
- Vaults V3 will be my focus on Monday, jmonteer has sent his review
  - https://github.com/yearn/yearn-devdocs/pull/291

*in other notes, I released the firs UI for DocuDroid! I'm abstracting away the prompts that help me do docs into this tool: http://worms.io/docudroid (requires a GPT key)

## Articles

- We got a review from Lido and published the article this week!
  - https://medium.com/iearn/yearn-strategies-case-study-lido-staked-eth-d21b2a57f79c
  - https://twitter.com/iearnfinance/status/1610640927701487616
![image](https://user-images.githubusercontent.com/7863230/211070437-3790346b-ce58-4cea-91da-a1c88261a4cd.png)

## Vault Report

- Generated December report! idk where it's being published but if I find a link I paste here
- Applied change requests forwarded by Toby Tiger

![report (4)](https://user-images.githubusercontent.com/7863230/211071003-16863ff3-94e2-42c4-9982-854f18c2550b.png)

**Comment by MarcoWorms** [comment]
ty @0xValJohn we have fixed the issue for the next one!

**Comment by MarcoWorms** [comment]
## Docs

- finished Dank Mids doc with BobtheBuilder and made a callout twitter post for it
  - https://github.com/BobTheBuidler/dank_mids/pull/39
  - https://twitter.com/MarcoWorms/status/1612569733664051200<br/><br/>
- Iterated v3 docs, still ongoing process with ghosty and jmonteer, this week I fixed all the comments jmonteer left that I could act on
  - https://github.com/yearn/yearn-devdocs/pull/291<br/><br/>
- working on exporter docs, now making a banner image for it
  -  https://github.com/yearn/yearn-exporter/pull/458 <br/><br/>
- trying to get these 2 merged, hopefully next week! They are like 99% done:
  - https://github.com/yearn/yearn-devdocs/pull/297
  - https://github.com/yearn/yearn-devdocs/pull/298

## Articles
- Protecting yields with Yearn + Ledger initial draft is here, I'm checking with DarkGhosty to see what could improve bc I think it can still improve
  - https://hackmd.io/FEUufpxRRWyZg7GbaTnJ-Q

## Vault Report
- Applied design and info change requests made along the week, available to fix any other issues/feedback here!

**Comment by MarcoWorms** [comment]
## Docs

- restructure data services in docs to add yearn-exporter
  - https://github.com/yearn/yearn-devdocs/pull/304
- remade partner tracker PR to fix issues
  - https://github.com/yearn/yearn-devdocs/pull/297
- improve risk-score copywriting, this doc is linked by many recent articles, corn revied It I fixed all points now needs approval
  - https://github.com/yearn/yearn-devdocs/pull/298

## Articles

There are 2 ongoing articles, both still need work I got reviews on the ledge one I need to restructure it:

- Protect your yields with Ledger and Yearn
  - https://hackmd.io/FEUufpxRRWyZg7GbaTnJ-Q
- (very WIP) Yearn Vault Factory
  - https://hackmd.io/Wf3aJlPAReerUFWwjyxn2w

## Others

- coordinated twitter thread with steve0xp that should come out Monday and be RTed by yearn accs, it goes over the main points of our last article about lido to try to get more people to read it!
- available to apply any fixes to vault reports!
- monitoring support channels and forums to answer and learn more about what our users need atm so I can find more things to write about!

**Comment by MarcoWorms** [comment]
## Docs

all PRs from last week were merged!!! Only V3 vaults is on-hold for whenever we deploy the product we merge this so docs go live

- https://github.com/yearn/yearn-devdocs/pull/297
- https://github.com/yearn/yearn-devdocs/pull/298
- https://github.com/yearn/yearn-devdocs/pull/304

Started tackling an old issue in the repo:
- https://github.com/yearn/yearn-devdocs/pull/305

## Articles

- Vault Factory draft is done, sending for reviews now!
  - https://hackmd.io/Wf3aJlPAReerUFWwjyxn2w
- Ledger article draft did not change since last week, still needs restructure

## Others

- steve deployed the thread we coordinated last week:
  - https://twitter.com/steve0xp/status/1617945426103267329
- (as always,) available to apply any fixes to vault reports! Next week we should generate JAN stats :)
- I used GPT to answer a support question by passing one of our docs to it + pasting the users question. The answer was satisfactory enough tbh (I did edit it, but the core was correct), I am working on how to upload the entirety of yearn docs as a GPT embedding so we can have some sort of yGenius support robot that know how to answer things based in our docs and articles!

**Comment by MarcoWorms** [comment]
## Docs
I'm working on a GPT index with all yearn docs, articles, yips, relevant social chatter, so we can have a tool that helps answering stuff around yearn

as Drapper would put: "Get to know Yearn, without having to speak to a dev."

Current index contains devdocs and UI is very poor at http://worms.io/ygenius

But Evan will help me make a better UI while I work on improving the index!

<img width="1529" alt="Screen Shot 2023-02-03 at 4 20 58 PM" src="https://user-images.githubusercontent.com/7863230/216689218-d2d3da26-6001-43a7-a81a-2906941118e3.png">

## Articles

Vault factory article still under review: https://hackmd.io/Wf3aJlPAReerUFWwjyxn2w

## Vault report

Did not receive data for Jan yet, but I'm available to generate the report whenever we have it!

**Comment by MarcoWorms** [comment]
## Docs

- We can release https://ygenius-webui.yearn.farm/ next week IMO, this week I finished UI + initial Index, now we have tons of things to refine. Sources:
  - Backend: https://github.com/yearn/ygenius-brain
  - Frontend: https://github.com/yearn/ygenius-webui

![image](https://user-images.githubusercontent.com/7863230/218208096-e88a1b32-85e3-4cd3-a8bf-3c80d48d918c.png)

## Articles
- Built an article for the release above: https://hackmd.io/dh9_PB8USR6wgqezpltwVA?view

## Vault Reports
- Did not receive Jan data yet, but ready to build the report once we have the data!

**Comment by MarcoWorms** [comment]
## Docs

First version of yGenius with all docs + articles + support history channel is deployed! The cool thing is that it was already able to find improvements in docs through its answers, for example this one: https://github.com/yearn/yearn-devdocs/issues/307

**Release Posts:**
- https://twitter.com/MarcoWorms/status/1625220002713313280
- https://twitter.com/iearnfinance/status/1625492137675722757

**Release Article:**
- https://medium.com/@marcoworms/ygenius-chat-with-yearn-efa17d3f0ec8

**Links**
- App: https://ygenius-webui.yearn.farm/
- Backend Source: https://github.com/yearn/ygenius-brain
- Frontend Source: https://github.com/yearn/ygenius-webui

## Articles

Have 2 ongoing articles that were a bit paused bc of my focus on ygenius, one is under review another I'm editing, should release one of them by next week:

- vault factories: https://hackmd.io/Wf3aJlPAReerUFWwjyxn2w
- yearn + ledger: https://hackmd.io/FEUufpxRRWyZg7GbaTnJ-Q?both

**Comment by MarcoWorms** [comment]
I am at ETHDenver in the next 2 weeks, and this grant is expiring soon!

The followup grant can be found here, will continue reporting there if it passes https://github.com/yearn/budget/issues/112

yGenius has passed through some cool upgrades since release in the last couple weeks, I'd recommend trying again! https://ygenius.yearn.farm/

There are still many rough edges but answers are getting better, I am coordinating with some support people to make sure it is useful for them to answer real user questions, I won't write a more detailed report today because I'm busy at the event!

Working on yETH docs too, should be done the next couple days at least a robust draft so next week it gets reviewed and pass through the team scrutiny
