### ISSUE TITLE
Continue Funding the Frontend Team [extension]

### ISSUE THREAD

**Issue by saltyfacu** [yearn/budget#104]
### Scope

The frontend team continues to have a series of projects in different statuses and with different requirements. The scope of this request is to maintain the currently finished UI projects, continue improving the projects under active development, and start new ones as we finish the ones we are working on. 

Below there's a list of the projects under the frontend team.

#### Done / Low Maintenance
 - yearn-issues
 - ape.tax
 - yBuybacks
 - Yearn comms
 - Vaults at Yearn
 - yHack
 - ySync
 - NFTreasury
 - yWorld
 - yBrand
 - Macarena.finance
 - Bowswap

#### Under active development
 - Web lib | Web Template
 - Yearn SDK
 - yearn.watch
 - yearn.finance
 - yVempire | yMigrate
 - B2B Dashboard
 - veYFI
 - yCRV
 - yBribe

### Plan

The plan is to focus on the projects under development. veYFI is the main priority right now, followed by Yearn.watch. We will continue to improve its reliability and get the projects to the finish line. The team will fund contributors via bounties, using part of this grant.

We don't want to do streams yet, but to send the funds to contributors at the end of the month. We will leverage bounties for small tasks. All the details will be shared in comments at the end of the month, as we've been doing in #70 and #91

### Deadline

2023-02-28

### People

Gambito: leading some of the projects - no funding from this budget
Major: leading some of the projects - no funding from this budget
saltyfacu: just writing this proposals - no funding from this budget
Chef: dev
0xMirim: dev

Other freelancers via bounties

### Money

We plan to distribute a grant for each person in charge of a project and use bounties to fund other contributions linked to projects in maintenance mode or isolated contributions.

### Amount

30000 DAI

### Wallet address

0x0

### Reporting

Monthly

**Comment by karelianpie** [comment]
# November 2022 Update

## yCRV

Final touches on the Wido integration, PR review:

https://github.com/yearn/yCRV/pull/26
https://github.com/yearn/yCRV/pull/38

## ySync

New features in ySync, now partners in exporter are mirrored in yDaemon and there's a check so see if every vaults' want token has a description:

https://github.com/yearn/ySync/pull/78
https://github.com/yearn/ySync/pull/79

## yDaemon

Minor work on yDaemon related to https://github.com/yearn/ySync/pull/78#issuecomment-1303838232

https://github.com/yearn/ydaemon/pull/115
https://github.com/yearn/ydaemon/pull/125

## Web lib

Substancial improvement related to TypeScript in the web lib codebase:

https://github.com/yearn/web-lib/pull/109
https://github.com/yearn/web-lib/pull/114
https://github.com/yearn/web-lib/pull/115

## Yearn Issues

Fixed a bug that was prevent the good first issue page from loading:

https://github.com/yearn/yearn-issues/pull/18

## Yearn Comms

Implemented deep-linking with anchor link support for headings, fixed the greeting GitHub action and bug related to `og:image`:

https://github.com/yearn/yearn-comms/pull/1511
https://github.com/yearn/yearn-comms/pull/1514
https://github.com/yearn/yearn-comms/pull/1518
https://github.com/yearn/yearn-comms/pull/1520

## yMigrate

Started a greenfield project to have a nicer bowswap. The final outcome would be to have a single web app to zap from aave, curve, beefy, compound, stakedao, etc. to Yearn.

https://github.com/yearn/yMigrate

**Comment by 0xMirim** [comment]
## Partner Dashboard 

This month was productive. I spent all my time focused on the partner dashboard, specifically finalizing and transforming most of the dashboard placeholders into robust working components that are ready to use real partner data.

I also reached the point where I needed feedback and started conversations with Evan Kox (design), as well as members of the b2b dashboard telegram group for feedback on functionality and data sourcing concerns. 

I'm finishing the month focused on sourcing the real data to use as input to generate the chart visuals. This started with investigating yDaemon which didn't have the required partner data, and evolved into an investigation of the yearn exporter. I've brushed up on docker and learned the basics of grafana and victoriametrics. I've also reviewed a fair amount of exporter code related to how to query partner data. I'm planning to begin a conversation with Bob the Builder or Marius shortly for additional clarity. 

[Link to current dashboard demo](https://b2b-dashboard-5ff2fsfwu-ycorpo.vercel.app/dashboard) - Screenshots also included below.

Overview of Code Changes
* https://github.com/Majorfi/b2b-dashboard/pull/58
   - Added report date range selection and validation
   - Made data window (1 day, 1 week, etc) dynamic, causing charts to be re-rendered on change
   - Added Wrapper Balance and Aggregate Wrapper Balance Distribution charts (challenging to setup properly)
   - Added proper display and formatting of x and y axis values as well as custom tool-tip and chart tick values
   - Many refactors to increase component flexibility (Tooltip, Legend, etc) and various bug fixes 

---

<img width="1424" alt="charts-01" src="https://user-images.githubusercontent.com/95051992/204288374-3f05ea4f-c535-44bd-9766-24ee321f3678.png">


<img width="1440" alt="charts-02" src="https://user-images.githubusercontent.com/95051992/204288684-f0861168-77ca-4789-8c23-028fe669bca9.png">

**Comment by ai-slave** [comment]
Was passing by, thought I could help and so decided to do so :) 
I was getting familiar with the codebase and picked up a global settings task which required to dive into multiple projects and update some codebase while introducing the ability to change project settings like API server urls and so on. 
I achieved what we planned together with Major (thank you for guiding me!). Here's a quick summary:

### yCRV
Introduced settings block
* https://github.com/yearn/yCRV/pull/42 – turned out it wasn't needed
* https://github.com/yearn/yCRV/pull/45

### web-template 
Reported bug
* https://github.com/yearn/web-template/issues/63

### Yearn Watch
Introduced settings block, fixed bug with vault names.
* https://github.com/yearn/yearn-watch/pull/134
* https://github.com/yearn/yearn-watch/pull/136

### ySync
Introduced settings block 
* https://github.com/yearn/ySync/pull/82

### yBribe 
Introduced settings block, migrated env variables to settings 
* https://github.com/yearn/yBribe/pull/4

### Yearn v3
Fixed UI bug
* https://github.com/yearn/yearn-finance-v3/pull/790

**Comment by 0xMirim** [comment]
## Partner Dashboard 

My full focus remained the partner dashboard, specifically working to source the correct data to create dynamic partner specific UI for the dashboards.

This report is more verbose than usual as the early part of the month was spent largely exploring data and troubleshooting data issues, which didn't result in commits. While not especially fast the important thing is that the overall effort was successful and I now have the clarity required to tackle data related tasks much faster in the future. 

I began the month with efforts to run my own exporter instance on a remote host. On multiple days I became blocked with issues related to RPCs but with the assistance of Bob, and Marius I was able to solve these. 

Running my own exporter seemed like the best idea early on because it would allow me admin access to configure Grafana dashboards, as well as the ability to explore relevant partner metrics. This was necessary because no such visuals had been setup on the production Grafana dashboard, and the production metrics explorer wasn't available without admin access.

About mid-month was the first time I synced with Dark and after hearing about my needs, and previous efforts, he provided me admin access to the exporter dev / staging area, where he had already configured Grafana visuals for partner metrics. This was appreciated, saved me time, and allowed me to consult metrics on-demand.

From there I spent time considering which queries I would need to send to retrieve the desired data on the front-end. My preliminary use-case was retrieving what vaults a partner was in to dynamically generate dashboard tabs. I used the Insomnia REST client to test a variety of queries and see what would get returned and in what format. Everything worked fine.

Towards the end of the month, content with my data wrangling efforts, I returned to front-end dashboard work. It had been a while since dependencies had been updated so I started there. Next I followed Major's advice and upgraded the tabs, to replace the web-lib implementation, as well as allow the addition of new actions (copy address, and view address on explorer). I then started work on a usePartner context to allow efficient query and application wide sharing or relevant partner data once retrieved. 

Next I started making data requests from the front-end only to face blocked requests due to CORS configuration of the exporter-api. I was blocked here for a while until Marius suggested running the exporter-api locally with an adjusted CORS config. I was able to do this and succeeded in setting up a dev environment that would access the API data without issue. 

I spent about a day adjusting the exporter-api to parse and return data in a format that was easier to use on the front-end. I ended up determining that such an approach wasn't worth the effort and implemented logic to do necessary transformation on the front-end. 

I ended the month by pushing an implementation of dynamic vault tabs on each partners dashboard. When a dashboard is visited it will show one tab for each vaults that partner is in. The tab name includes the vault token and the network the vault is on. In the case no data exists simple UI to show "No vaults found" is show, a loading state is also shown while vaults are being retrieved.


#### Overview of Code Changes

* https://github.com/Majorfi/b2b-dashboard/pull/80
   - Added dynamic vault tabs showing vault token and network to each partner dashboard
   - Added usePartner context for efficient data, retrieval, storage, and app wide sharing
   - Added new approach to Tabs which includes additional actions on the tabs bar
   - Added basic UI for no vaults found, and vault loading state on each dashboard
   - Refactors to better organize files and various bug fixes 
   - Updated dependencies


---


<img width="1429" alt="vaultTabs" src="https://user-images.githubusercontent.com/95051992/210072664-230827a3-8252-4a2f-a48b-2a90c298728c.png">

**Comment by karelianpie** [comment]
Monthly Report 12.2022

## yCRV

* https://github.com/yearn/yCRV/issues/32

## Web lib

* https://github.com/yearn/web-lib/pull/134
* https://github.com/yearn/web-lib/pull/137
* https://github.com/yearn/web-lib/pull/138
* https://github.com/yearn/web-lib/pull/139
* https://github.com/yearn/web-lib/pull/140
* https://github.com/yearn/web-lib/pull/141
* https://github.com/yearn/web-lib/pull/142
* https://github.com/yearn/web-lib/pull/145

## Yearn.fi

* https://github.com/yearn/yearn.fi/pull/5
* https://github.com/yearn/yearn.fi/pull/7
* https://github.com/yearn/yearn.fi/pull/6
* https://github.com/yearn/yearn.fi/pull/8
* https://github.com/yearn/yearn.fi/pull/9
* https://github.com/yearn/yearn.fi/pull/10
* https://github.com/yearn/yearn.fi/pull/12
* https://github.com/yearn/yearn.fi/pull/14
* https://github.com/yearn/yearn.fi/pull/15
* https://github.com/yearn/yearn.fi/pull/21
* https://github.com/yearn/yearn.fi/pull/16

## Yearn Watch

* https://github.com/yearn/yearn-watch/pull/138
* https://github.com/yearn/yearn-watch/pull/139

## Web Template

* https://github.com/yearn/web-template/pull/68

**Comment by 0xMirim** [comment]
## Partner Dashboard 

This month focused on using the data that was sourced last month to implement real charts using live data. We now have the actual aggregate wrapper balance chart on each dashboards Overview tab, as well as vault specific wrapper balance chart on each vaults tab. 

#### Overview of Code Changes

* https://github.com/Majorfi/b2b-dashboard/pull/90
    - Added live metrics for fees, tvl, partner count to the home page
    - Added wrapper balance chart (with live data) on all vault tabs (for 7, 29, and 50 day time frames)
    - Added aggregate wrapper balance chart (with live data) on dashboard overview tab
    - Added live metrics for tvl, fees, apy, and risk score to each vault tab on dashboard
    - Added Ability to copy vault address and view vault on block explorer from dashboard page
    - Improved chart legends and tooltip to dynamically handle real chart values
    - Added content for learn more and team up pages
    - Many small changes, refactors, and bug fixes
---

Chart showing the balance of a specific partners wrapper contract over time, as well as vault metrics

<img width="1430" alt="wrapperBalance" src="https://user-images.githubusercontent.com/95051992/215781529-9a244c43-e79d-4cf7-b1ad-1c24587befbb.png">

Aggregate wrapper balance chart for a partner showing their profit share tier change overtime based on the sum of their wrapper balance across all tracked vaults. 

<img width="1429" alt="awb" src="https://user-images.githubusercontent.com/95051992/215781570-8d2b3c9e-ee5f-478a-a261-83c09d4912e2.png">

**Comment by Itzabelli** [comment]
### January Report 

Hello, I am new here, @0xMirim recently told me about your project and I am very interested, so I decided review it to see if it was possible to contribute to it. I thought I'd to start with some small things, I hope to be able to continue bringing more significant changes that meet the objectives or needs of the organization.

 ## Yearn Finance

* https://github.com/yearn/yearn.fi/pull/44 
* https://github.com/yearn/yearn.fi/pull/53


 ## B2B Dashboard

* https://github.com/Majorfi/b2b-dashboard/pull/101
* https://github.com/Majorfi/b2b-dashboard/pull/109


 ## Yearn Press Kit

 * https://github.com/yearn/yearn-press-kit/pull/79
 * https://github.com/yearn/yearn-press-kit/pull/84

**Comment by karelianpie** [comment]
Monthly Report 01.2023

## Yearn.fi

* https://github.com/yearn/yearn.fi/pull/30
* https://github.com/yearn/yearn.fi/pull/31
* https://github.com/yearn/yearn.fi/pull/32
* https://github.com/yearn/yearn.fi/pull/41
* https://github.com/yearn/yearn.fi/pull/43
* https://github.com/yearn/yearn.fi/pull/45
* https://github.com/yearn/yearn.fi/pull/59
* https://github.com/yearn/yearn.fi/pull/62
* https://github.com/yearn/yearn.fi/pull/69
* https://github.com/yearn/yearn.fi/pull/49

## Web lib

* https://github.com/yearn/web-lib/pull/156
* https://github.com/yearn/web-lib/pull/157
* https://github.com/yearn/web-lib/pull/158
* https://github.com/yearn/web-lib/pull/159
* https://github.com/yearn/web-lib/pull/160
* https://github.com/yearn/web-lib/pull/161
* https://github.com/yearn/web-lib/pull/162
* https://github.com/yearn/web-lib/pull/164
* https://github.com/yearn/web-lib/pull/170
* https://github.com/yearn/web-lib/pull/174

## yBuyback

* https://github.com/yearn/yBuyback/pull/51
* https://github.com/yearn/yBuyback/pull/52
* https://github.com/yearn/yBuyback/pull/53
* https://github.com/yearn/yBuyback/issues/50

**Comment by Itzabelli** [comment]
### February Report

Hello! This month was good I continued looking at various Yearn repos and trying to identify and resolve small issues. I feel like I have a good understanding of some of the repos and plan to focus more of my time on b2b-dashboard moving forward as it was not too difficult to understand and there seems to be things to do there that match my skill level. 

## Yearn Finance

- https://github.com/yearn/yearn.fi/pull/77

## B2B Dashboard

- https://github.com/Majorfi/b2b-dashboard/pull/113
- https://github.com/Majorfi/b2b-dashboard/pull/117
- https://github.com/Majorfi/b2b-dashboard/pull/114

## Yearn Genius

- https://github.com/yearn/ygenius-webui/pull/5
- https://github.com/yearn/ygenius-webui/pull/10
- https://github.com/yearn/ygenius-webui/pull/12

## Yearn Daemon

- https://github.com/yearn/ydaemon/pull/215

## Issues

I opened these issues early in the month and then focused on other tasks. I think I see possible solutions and I will be submitting solutions to these issues soon. 

## Yearn Press Kit

- https://github.com/yearn/yearn-press-kit/issues/85
- https://github.com/yearn/yearn-press-kit/issues/86

**Comment by karelianpie** [comment]
Monthly Report 02.2023

## Yearn.fi

* https://github.com/yearn/yearn.fi/pull/49
* https://github.com/yearn/yearn.fi/pull/79
* https://github.com/yearn/yearn.fi/pull/81
* https://github.com/yearn/yearn.fi/pull/72 (review)
* https://github.com/yearn/yearn.fi/pull/56 (review)

## ySync

* https://github.com/yearn/ySync/pull/84

## yGenius

* https://github.com/yearn/ygenius-webui/pull/3

## Web lib

* https://github.com/yearn/web-lib/pull/181

## yIssues

* https://github.com/yearn/yIssues/pull/3
* https://github.com/yearn/yIssues/pull/4

**Comment by 0xMirim** [comment]
## Partner Dashboard 

The focus of this month was to reach a near feature complete version of the b2b-dashboard. I worked hard to make this a reality and am proud to say that we are very close at this point. Only a few things small things needed to be carried forward, then focus will shift to polishing and preparing for a production release.

All charts required for release have been added and only minor modifications are required at this point. Login needs to be finalized, but I'm working on it and should be done in the coming days. It's likely we'll be able to set a launch date within the next two weeks, with the idea to launch for the dashboard in mid-to-late March. 

#### Overview of Code Changes

* https://github.com/Majorfi/b2b-dashboard/pull/110
    - Added Wrapper Balance Distribution chart on Overview tab for all partners 
    - Added Individual Harvest Events chart on Overview tab and individual vault tabs for all partners
    - Added auto-generation of dashboard pages for all partners currently in the program
    - Added random shuffle when selecting the 9 partners to be displayed on the homepage
    - Added Aggregate Payout Totals chart on Overview tab for all partners 
    - Improved Tooltip and Legend components, added condensed legend concept for charts with many assets 
    - Many UI adjustments, code refactors, and bug fixes
 
## Yearn Exporter 
* https://github.com/yearn/yearn-exporter/pull/483
    - Adjusted Partners exporter to index data from the past instead of only being forward looking, supports b2b dashboard
---

Chart showing the Wrapper Balance Distribution charts now on all partners Overview tab.

<img width="1380" alt="wrapperBalanceDist" src="https://user-images.githubusercontent.com/95051992/221884920-5184563c-1bd8-4330-8615-b1ca8048ab00.png">

Chart showing Individual Harvest Events now on all partners Overview tab.

<img width="1348" alt="HarvestEvents" src="https://user-images.githubusercontent.com/95051992/221888088-383d7eda-7bc7-4e4b-a2f2-d1508a4079ee.png">

**Comment by saltyfacu** [comment]
Total spent: 28.429 DAI
