### ISSUE TITLE
Continue Funding the Frontend Team [1 month extension]

### ISSUE THREAD

**Issue by saltyfacu** [yearn/budget#116]
### Scope

The frontend team continues to have a series of projects in different statuses and with different requirements. The scope of this request is to maintain the currently finished UI projects, continue improving the projects under active development, and start new ones as we finish the ones we are working on. 

Below there's a list of the projects under the frontend team.

#### WORKING ON RIGHT NOW
- Web lib | Web Template
- yearn.finance
	- OP staking
	- yETH
- yDaemon
- B2B Dashboard

#### Done / Low Maintenance
- yearn.finance
	- yCRV
	- yBribe
	- veYFI
- yearn-issues
- ape.tax
- yBuybacks
- Vaults at Yearn
- yHack
- ySync
- NFTreasury
- yWorld
- yBrand
- Macarena.finance
- Bowswap
- yVempire | yMigrate
- Yearn SDK

### Plan

The plan is to focus on the projects under development. veYFI is the main priority right now, followed by Yearn.watch. We will continue to improve its reliability and get the projects to the finish line. The team will fund contributors via bounties, using part of this grant.

We don't want to do streams yet, but to send the funds to contributors at the end of the month. We will leverage bounties for small tasks. All the details will be shared in comments at the end of the month, as we've been doing in #70, #91 and #104

### Deadline

2023-03-31

### People

Chef
0xMirim

Other contributors via bounties

### Money

We plan to distribute a grant for each person in charge of a project and use bounties to fund other contributions linked to projects in maintenance mode or isolated contributions.

### Amount

12000 DAI

### Wallet address

0x0

### Reporting

Monthly

**Comment by 0xMirim** [comment]
## Partner Dashboard 

B2B dashboard was successfully launched on March 20th (which was our internally set released date). Everything went smoothly and we're nearing the two week mark of having the app stable in production.

Since launch two sets of improvements have been made. The first was mainly UI adjustments to improve the mobile experience and has been merged. The second set, which is still currently awaiting review, are for enhancements that have been requested (see details below)

In my opinion the only important feature that remains to be completed is ability to download data via csv (this wasn't required for launch) and will be a task I focus on next month, beyond that I'd consider the project completed. 


#### Overview of Code Changes:

* https://github.com/yearn/b2b-dashboard/pull/125
  - Implemented auth using specific partner addresses
  - Many pre-launch adjustments: work with team to set fixed domain, resolve code review feedback, etc
  - Many UI adjustments, code refactors, and bug fixes
  - Adjusted to more sustainable approach (smaller PRs)

* https://github.com/yearn/b2b-dashboard/pull/151
    - Solved issue related to data back-filling that caused a small subsets of dashboards to crash 
    
* https://github.com/yearn/b2b-dashboard/pull/164
    - Adjust dashbord urls to be easily sharable, remove previous url format using partner names

* https://github.com/yearn/b2b-dashboard/pull/162
 
---


## Code Review

I was involved in reviewing and approving / requesting changes for a variety of PRs related to B2B.

- https://github.com/yearn/b2b-dashboard/pull/163#pullrequestreview-1363035225
- https://github.com/yearn/b2b-dashboard/pull/160#pullrequestreview-1352896249
- https://github.com/yearn/b2b-dashboard/pull/161#pullrequestreview-1352851098
- https://github.com/yearn/b2b-dashboard/pull/153#pullrequestreview-1348891612
- https://github.com/yearn/b2b-dashboard/pull/154#pullrequestreview-1348520062
- https://github.com/yearn/b2b-dashboard/pull/140#pullrequestreview-1337645049
- https://github.com/yearn/b2b-dashboard/pull/139#pullrequestreview-1337099795
- https://github.com/yearn/b2b-dashboard/pull/136#pullrequestreview-1334955429
- https://github.com/yearn/b2b-dashboard/pull/137#pullrequestreview-1334514556
- https://github.com/yearn/b2b-dashboard/pull/138#pullrequestreview-1334356445
- https://github.com/yearn/b2b-dashboard/pull/126#pullrequestreview-1326509883

**Comment by Itzabelli** [comment]
### March Report

Hello! This month I tried to focus my efforts on b2b-dashboard, resolving a few issues suggested by team and identifying things that could help to improve the UI.

## B2B Dashboard

- https://github.com/yearn/b2b-dashboard/pull/137
- https://github.com/yearn/b2b-dashboard/pull/154
- https://github.com/yearn/b2b-dashboard/pull/152
- https://github.com/yearn/b2b-dashboard/pull/160
- https://github.com/yearn/b2b-dashboard/pull/161
- https://github.com/yearn/b2b-dashboard/pull/153
- https://github.com/yearn/b2b-dashboard/pull/126
- https://github.com/yearn/b2b-dashboard/pull/136
- https://github.com/yearn/b2b-dashboard/pull/138
- https://github.com/yearn/b2b-dashboard/pull/139
-  https://github.com/yearn/b2b-dashboard/pull/140
-  https://github.com/yearn/b2b-dashboard/pull/163

## Yearn Genius

- https://github.com/yearn/ygenius-webui/pull/14
   - Early in the month I submitted a fix for an issue with my original PR

## Yearn Press Kit

- https://github.com/yearn/yearn-press-kit/pull/98
    - I discovered a visual issue and submitted a potential solution

**Comment by karelianpie** [comment]
Monthly Report 03.2023

## Yearn.fi

* https://github.com/yearn/yearn.fi/pull/79
* https://github.com/yearn/yearn.fi/pull/84
* https://github.com/yearn/yearn.fi/pull/86
* https://github.com/yearn/yearn.fi/pull/88
* https://github.com/yearn/yearn.fi/pull/89
* https://github.com/yearn/yearn.fi/pull/91
* https://github.com/yearn/yearn.fi/pull/101
* https://github.com/yearn/yearn.fi/pull/102
* https://github.com/yearn/yearn.fi/pull/104
* https://github.com/yearn/yearn.fi/pull/109
* https://github.com/yearn/yearn.fi/pull/110
* https://github.com/yearn/yearn.fi/pull/114
* https://github.com/yearn/yearn.fi/pull/118
* https://github.com/yearn/yearn.fi/pull/119
* https://github.com/yearn/yearn.fi/pull/120
* https://github.com/yearn/yearn.fi/pull/122

## yIssues

* https://github.com/yearn/yIssues/pull/3
* https://github.com/yearn/yIssues/pull/4

## Yearn Watch

* https://github.com/yearn/yearn-watch/pull/141
* https://github.com/yearn/yearn-watch/pull/142
* https://github.com/yearn/yearn-watch/pull/144

## yDaemon

* https://github.com/yearn/ydaemon/pull/222
* https://github.com/yearn/ydaemon/issues/225

## Web Lib

* https://github.com/yearn/web-lib/pull/194
* https://github.com/yearn/web-lib/pull/197
* https://github.com/yearn/web-lib/pull/204
* https://github.com/yearn/web-lib/pull/206
* https://github.com/yearn/web-lib/pull/209
* https://github.com/yearn/web-lib/pull/210
* https://github.com/yearn/web-lib/pull/211

## Web Template

* https://github.com/yearn/web-template/pull/81

## ySync

* https://github.com/yearn/ySync/pull/86
* https://github.com/yearn/ySync/pull/88
* https://github.com/yearn/ySync/pull/89

## CoW Protocol

* https://github.com/cowprotocol/contracts/pull/44
