### ISSUE TITLE
Continue Funding the Frontend Team

### ISSUE THREAD

**Issue by saltyfacu** [yearn/budget#91]
### Scope

The frontend team continues to have a series of projects in different statuses and with different requirements. The scope of this request is to maintain the currently finished UI projects, continue improving the projects under active development, and start new ones as we finish the ones we are working on. 

NFT Treasury was a new project during last request, and now is finished. Yearn World, Yearn Brand and Macarena, were started and finished also. A few new projects popped up with high priority and we are already working on them.

Below there's a list of the projects under the frontend team.

#### Done / Low Maintenance
- yearn-issues
- ape.tax
- yBuybacks
- Yearn comms
- Vaults at Yearn
- yHack
- yDataSync
- NFTreasury
- Yearn World
- Yearn Brand
- Macarena.finance
- Bowswap

#### Under active development
- Web lib
- Yearn SDK
- yearn.watch
- yearn.finance
- veYFI
- Curve related product
- yVempire 🦇

#### New
- B2B Dashboardnew ones

### Plan

The plan is to focus on the projects under development and NFTreasury. veYFI and the Curve related project are the main priorities right now, followed by Yearn.watch. We will continue to improve its reliability and get the projects to the finish line. The team will fund contributors via bounties, using part of this grant.

Stretching the last budget of 25.000 DAI, we made it last 3 months instead of one, with a residual amount of almost 9.000 DAI. This time, with more data, we are asking for a budget that will cover three months.

We don't want to do streams yet, but to send the funds to contributors at the end of the month. We will leverage bounties for small tasks. All the details will be shared in comments at the end of the month, as we've been doing in #70 

### Deadline

2022-11-30

### People

Gambito: leading some of the projects - no funding from this budget
Major: leading some of the projects - no funding from this budget
saltyfacu: helping out with the organizational part - no funding from this budget
Chef: UI dev
Marco Worms: UI dev
0xMirim: UI dev
Nova: UI dev

Other freelancers via bounties

### Money

We plan to distribute a grant for each person in charge of a project and use bounties to fund other contributions linked to projects in maintenance mode or isolated contributions.

### Amount

30000 DAI

### Wallet address

0x0

### Reporting

- [X] I agree to post weekly updates

**Comment by 0x7171** [comment]
Thanks for the request!

Reading the post, it looks like you spent `(25k-9k)/3 = 5.33k DAI/mo` the previous quarter. 

For this quarter, you are now requesting a budget of 30k DAI, making the total amount available to spend `(30k+9k)/3 = 13k DAI/mo`, a 143% increase. 

What's the motivation and rationale behind this increase?

**Comment by saltyfacu** [comment]
Great question. Sorry that this was not clear in my request. The 30k is the total amount asked for, including the pending ~9k. 

Without those 9k, it still seems to be ~100% increase, but truth is that the first few months were slower.

Last month we spent 9.5K and that's the level we are going to keep. We are asking for a 5% buffer in case we have any minor deviation.

**Comment by MarcoWorms** [comment]
weekly report

## yDaemon

Fixed grammar/typos over the docs:

- https://github.com/yearn/ydaemon/pull/42

## yfu

Applied all audit reviews about the code itself https://github.com/MarcoWorms/yfu-contracts/pull/8

The missing issues now to be tackled are about raising a Foundry/Hardhat environment in order to make a deployer script and not rely on remix so we can add a couple of checks like "IPFS link should have / in the end on deploy", also make part of the checklist become automated tests

## web-lib

Working on documenting CSS features, found a small blocker where we don't have a simple place to show all themes examples so I should make one at codesandbox

Dev branch at: https://github.com/yearn/web-lib/commit/b16d99fea1b6528193324e3f615572bed8d82d1d

## yearn vaults balance UI

I was not able to focus on this this week because I'm more afk then usual due to an event, but I should have an UI mock by next week and I got y-e to run locally already for the data and bobthebuilder said he can help me if I have any issues with [yrs-backend](https://github.com/BobTheBuidler/yrs-backend) (which has the data we need)

**Comment by MarcoWorms** [comment]
## yearn vaults balance UI

- draft https://codesandbox.io/s/gifted-wu-ifybjv?file=/pages/index.tsx

- current state (no backend yet):
![image](https://user-images.githubusercontent.com/7863230/192037686-235d0eaa-dad1-4d0c-bb01-2d9bfb17296f.png)

- desired state:
![image](https://user-images.githubusercontent.com/7863230/192037729-75e4d97f-ad49-44e3-a4cc-ccbb79a6c2df.png)

## web-lib

because the above uses web-lib I'm tidying up the docs with all the hurdles I had trying to set it up from scratch

- https://github.com/yearn/web-lib/pull/90
- https://github.com/yearn/web-lib/pull/92

## yfu

I did not progress much on this scope, but I asked for Major's help this week and I didn't follow up to see if he tackled it, will report with more details next week

**Comment by karelianpie** [comment]
Monthly Report 09.2022

## ySync

Substancial amount of work on ySync this month, mainly detecting the absence of files and translations in [yearn-meta](https://github.com/yearn/yearn-meta)

* https://github.com/yearn/ySync/pull/54
* https://github.com/yearn/ySync/pull/55
* https://github.com/yearn/ySync/pull/57
* https://github.com/yearn/ySync/pull/62
* https://github.com/yearn/ySync/pull/65
* (WIP) https://github.com/yearn/ySync/pull/71

## web-template

Small PR to add a PR template to make reviewing PRs a bit more effective

* https://github.com/yearn/web-template/pull/56

## yearn-watch

Subgraph link should point to the currently selected network's active subgraph

* https://github.com/yearn/yearn-watch/pull/119

## NFTreasury

Closed the last two remaining issues, start making use of Yearn's subgraph

* https://github.com/yearn/NFTreasury/pull/59
* https://github.com/yearn/NFTreasury/pull/60

## yearn-finance-v3

Spike/discovery on a potential electron desktop app for the FE

* https://github.com/yearn/yearn-finance-v3/pull/749

**Comment by 0xMirim** [comment]
Not as much to report for September as I wasn't able to dedicate as much time as usual. Most of the effort I was able put in was invested in getting up to speed and making small to moderate impact updates to yVempire. I also reviewed the code diff for a dependency update in the yearn-vault-descriptions repo, and continued cleaning up miscellaneous small issues. More details below. 

## yVempire

I decided to shift my focus on yVempire after hearing it would be a priority moving forward. 

- https://github.com/Majorfi/yVempire/pull/1
  - A breaking change in the web-lib dependency (npm scope changed) made it such that new collaborators couldn't run the code. I manually updated web-lib, version by version, and corrected issues as they arose to bring the repo up to speed with the latest web-lib version.
- https://github.com/Majorfi/yVempire/pull/4
- https://github.com/Majorfi/yVempire/pull/5
- https://github.com/Majorfi/yVempire/pull/3


## yearn-vault-descriptions

I submitted the following pull request at the end of August but spent a couple of hours on Sept 1st on a follow-up task to review the code diff (which ended up being large) between the versions to ensure nothing unusual was present.
- https://github.com/yearn/yearn-vaults-descriptions/pull/74#issuecomment-1234208757


## yearn-press-kit

- https://github.com/yearn/yearn-press-kit/pull/29
  - As I have previously done in other yearn repos I adjusted `.gitignore` to properly exclude files generated a build time

**Comment by ktgnova** [comment]
This month has been crazy, and I didn't have much free time to work on the project. However, I still worked on implementing the design system to web-lib and did research, trial and error, and a lot of figuring out how things work under the web-lib hood. I need to spend more time with it, and I will continue this work next month.

- https://github.com/yearn/web-lib/pull/78

**Comment by karelianpie** [comment]
Monthly Report 10.2022

## ySync

Continue the work from the previous month, adding protocol data and the pending state for incoming Ledger plugins

* https://github.com/yearn/ySync/pull/71
* https://github.com/yearn/ySync/pull/73
* https://github.com/yearn/ySync/pull/75

## Yearn Vaults Descriptions

Update the site to only pull in current strategies and not all strategies that are active.

* https://github.com/yearn/yearn-vaults-descriptions/pull/81

## Yearn V3

Helped solve compilation errors in the FE repo

* https://github.com/yearn/yearn-finance-v3/pull/770

## yCRV

The bulk of the work towards the end of the month was the [Wido](https://www.joinwido.com/) discovery/integration where a new box was added to be able to enter yCRV, st-yCRV and lp-yCRV from any (supported) asset from the user wallet (by zapping).

* https://github.com/yearn/yCRV/pull/26

A few PR reviews as welll

* https://github.com/yearn/yCRV/pull/28
* https://github.com/yearn/yCRV/pull/30
* https://github.com/yearn/yCRV/pull/35

**Comment by saltyfacu** [comment]
**Total spent: 22,693.75 DAI**
